name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclenche le déploiement lors des pushes sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn[standard] joblib pandas numpy shap lightgbm

    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku auth:token

    - name: Deploy to Heroku
      run: |
        heroku create ${{ secrets.HEROKU_APP_NAME }}
        git push heroku main
