name: Deploy to Heroku # Le nom de l'action GitHub, qui sera affiché dans l'interface GitHub Actions.

on:
  push:
    branches:
      - main  # Déclenche le déploiement lors des pushes sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest # Le job nommé deploy s'exécute sur une machine virtuelle Ubuntu
    
    steps:
    - uses: actions/checkout@v2 # Cette étape récupère le code source du dépôt GitHub, avec toutes les branches et l'historique complet 
      with:
        fetch-depth: 0  # Désactiver le shallow clone

    - name: Set up Python
      uses: actions/setup-python@v2 
      with:
        python-version: '3.8' # Cette étape installe la version 3.8 de Python sur la machine virtuelle.


    - name: Install dependencies
      run: | # Ce bloc exécute une série de commandes dans le shell.
        python -m pip install --upgrade pip   # Met à jour pip à la dernière version.
        pip install fastapi uvicorn[standard] joblib pandas numpy shap lightgbm # Installe les dépendances Python nécessaires à l'application 

    - name: Login to Heroku
      env: # : Ce bloc passe des variables d'environnement aux commandes suivantes. 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # pour authentifier la connexion à Heroku
      run: | # crée un fichier .netrc dans le répertoire de l'utilisateur avec les informations d'identification pour Heroku, permettant à git de se connecter automatiquement à mon compte Heroku sans demander de mot de passe.
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

    - name: Add Heroku remote
      run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git # Ajoute un remote Git nommé heroku pointant vers mon application Heroku, en utilisant le nom de l'application stocké dans les secrets de GitHub (HEROKU_APP_NAME).

    - name: Deploy to Heroku
      run: git push heroku HEAD:main # Pousse la branche main locale vers la branche main du dépôt distant sur Heroku, déclenchant ainsi le déploiement de l'application.

